name: CI/CD Pipeline for Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up existing directory
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_INSTANCE_IP }} "
            rm -rf /home/ubuntu/app
          "

      - name: Copy code to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r . ubuntu@${{ secrets.EC2_INSTANCE_IP }}:/home/ubuntu/app

      - name: Build and run Docker container on EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_INSTANCE_IP }} "
            cd /home/ubuntu/app
            docker build -t my-app .
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:5000 my-app
          "
